apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerberus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerberus
  template:
    metadata:
      labels:
        app: cerberus
    spec:
      containers:
      - name: cerberus
        image: cerberus:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo:27017"
        - name: DB_NAME
          value: "cerberus"
        - name: API_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cerberus-service
spec:
  selector:
    app: cerberus
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer