aws_cloudtrail:
    aws_region: Region
    error_code: ErrorCode
    error_message: ErrorMessage
    event_name: EventName
    event_source: EventSource
    request_parameters: RequestParameters
    response_elements: ResponseElements
    source_ip_address: SourceIp
    user_agent: UserAgent
    user_identity.principal_id: UserId
    user_identity.user_name: User
azure_ad:
    app_display_name: Application
    identity: User
    ip_address: IpAddress
    location: Location
    resource_display_name: Resource
    result_description: ResultDescription
    result_type: ResultType
    status: Status
    user_principal_name: User
dns:
    client: SourceIp
    query: QueryName
    query_class: QueryClass
    query_type: QueryType
    response: QueryResults
    response_code: ResponseCode
    server: DestinationIp
firewall:
    action: Action
    application: Application
    destination_address: DestinationIp
    destination_port: DestinationPort
    direction: Direction
    dst_ip: DestinationIp
    dst_port: DestinationPort
    nat_destination_ip: NatDestinationIp
    nat_source_ip: NatSourceIp
    protocol: Protocol
    rule_name: RuleName
    source_address: SourceIp
    source_port: SourcePort
    src_ip: SourceIp
    src_port: SourcePort
gcp_audit:
    caller_ip: SourceIp
    method_name: MethodName
    principal_email: User
    request: RequestParameters
    resource_name: ResourceName
    response: ResponseElements
    service_name: ServiceName
    status.code: StatusCode
    status.message: StatusMessage
generic:
    command: CommandLine
    dest_ip: DestinationIp
    dest_port: DestinationPort
    destination_ip: DestinationIp
    destination_port: DestinationPort
    event_type: EventID
    file: TargetFilename
    filename: TargetFilename
    filepath: TargetFilename
    hash: Hashes
    host: Computer
    hostname: Computer
    md5: Hashes
    process: Image
    process_name: Image
    sha256: Hashes
    source_ip: SourceIp
    source_port: SourcePort
    src_ip: SourceIp
    src_port: SourcePort
    timestamp: EventTime
    user: User
    username: User
linux_auditd:
    a0: CommandLine
    auid: User
    cmdline: CommandLine
    comm: Image
    cwd: CurrentDirectory
    euid: User
    exe: Image
    name: TargetFilename
    node: Computer
    pid: ProcessId
    ppid: ParentProcessId
    type: EventID
    uid: User
powershell:
    command_line: CommandLine
    context_info: ContextInfo
    host_application: HostApplication
    host_name: HostName
    host_version: HostVersion
    path: Path
    script_block_id: ScriptBlockId
    script_block_text: ScriptBlockText
    user_id: User
syslog:
    cn1: ProcessId
    cs1: Details
    cs2: Details
    dpt: DestinationPort
    dst: DestinationIp
    duser: TargetUserName
    facility: Channel
    fileHash: Hashes
    filePath: TargetFilename
    fname: TargetFilename
    host: Computer
    hostname: Computer
    message: Message
    pid: ProcessId
    program: Image
    proto: Protocol
    severity: Level
    spt: SourcePort
    src: SourceIp
    suser: User
webserver:
    body_bytes_sent: sc-bytes
    c-ip: c-ip
    cs(Referer): cs-referrer
    cs(User-Agent): c-useragent
    cs-bytes: cs-bytes
    cs-host: cs-host
    cs-method: cs-method
    cs-uri-query: c-uri-query
    cs-uri-stem: c-uri
    cs-username: cs-username
    cs-version: cs-version
    http_referer: cs-referrer
    http_user_agent: c-useragent
    remote_addr: c-ip
    remote_user: cs-username
    request_method: cs-method
    request_uri: c-uri
    sc-bytes: sc-bytes
    sc-status: sc-status
    server_name: cs-host
    status: sc-status
    time-taken: time-taken
windows_security:
    authentication_package_name: AuthenticationPackageName
    channel: Channel
    command_line: CommandLine
    computer: Computer
    current_directory: CurrentDirectory
    event_data: EventData
    event_id: EventID
    event_record_id: EventRecordID
    logon_process_name: LogonProcessName
    logon_type: LogonType
    new_process_name: Image
    parent_command_line: ParentCommandLine
    parent_process_id: ParentProcessId
    parent_process_name: ParentImage
    process_command_line: CommandLine
    process_id: ProcessId
    process_name: Image
    source_network_address: IpAddress
    source_port: IpPort
    subject_domain_name: SubjectDomainName
    subject_logon_id: LogonId
    subject_user_name: User
    target_domain_name: TargetDomainName
    target_user_name: TargetUserName
    user_data: UserData
    workstation_name: WorkstationName
windows_sysmon:
    command_line: CommandLine
    company: Company
    computer: Computer
    creation_utc_time: CreationUtcTime
    current_directory: CurrentDirectory
    description: Description
    destination_hostname: DestinationHostname
    destination_ip: DestinationIp
    destination_is_ipv6: DestinationIsIpv6
    destination_port: DestinationPort
    destination_port_name: DestinationPortName
    details: Details
    event_id: EventID
    event_type: EventType
    file_version: FileVersion
    hashes: Hashes
    image: Image
    image_loaded: ImageLoaded
    initiated: Initiated
    integrity_level: IntegrityLevel
    logon_guid: LogonGuid
    logon_id: LogonId
    original_file_name: OriginalFileName
    parent_command_line: ParentCommandLine
    parent_image: ParentImage
    parent_process_guid: ParentProcessGuid
    parent_process_id: ParentProcessId
    previous_creation_utc_time: PreviousCreationUtcTime
    process_guid: ProcessGuid
    process_id: ProcessId
    product: Product
    protocol: Protocol
    query_name: QueryName
    query_results: QueryResults
    query_status: QueryStatus
    signature: Signature
    signature_status: SignatureStatus
    signed: Signed
    source_hostname: SourceHostname
    source_ip: SourceIp
    source_is_ipv6: SourceIsIpv6
    source_port: SourcePort
    source_port_name: SourcePortName
    target_filename: TargetFilename
    target_object: TargetObject
    terminal_session_id: TerminalSessionId
    user: User
    utc_time: EventTime
